### ISSUE TITLE
Some users are not seeing the buttons "View Attestation" | "Edit Topic" | "Proposal Detail" | "Flag Topic"

### ISSUE THREAD

**Issue by opticalresolution** [ledgerleapllc/devxdao-backend#159]
Reported by: Wulf Kaal 

User ID: 5 can see the buttons at the top. 

User ID: 1302 can not see the buttons at the top when looking at the same proposal #486

**Comment by opticalresolution** [comment]
GP-489

**Comment by ledgerleapllc** [comment]
Source of this problem is from Discourse again. The backend is failing to register some users' forum_name to Discourse as username with proper discourse_user_id for some reason. Then Discourse rejects requests required to get data to show buttons. A new try/catch should be written to encompass both dxd and Discourse backend exceptions on staging to find out exactly what part is failing sometimes and prevent a user from perpetually failing to authenticate to their Discourse data.
